services:
  cardano-relay:
    image: ghcr.io/blinklabs-io/cardano-node:11.0.1-1
    container_name: cardano-relay
    environment:
      - NETWORK=preview
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    volumes:
      - cardano-relay-data:/data/db
      - cardano-relay-ipc:/ipc
      - .:/workspace
    working_dir: /workspace
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - relay.pool
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-bp:
    image: ghcr.io/blinklabs-io/cardano-node:11.0.1-1
    container_name: cardano-bp
    environment:
      - CARDANO_NODE_SOCKET_PATH=/ipc/bp.socket
      - CARDANO_NETWORK=preview
      - CARDANO_TOPOLOGY=/workspace/docker/bp-topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/ipc/bp.socket
      - CARDANO_BLOCK_PRODUCER=true
      - CARDANO_SHELLEY_KES_KEY=/workspace/keys/bp-keys/kes.skey
      - CARDANO_SHELLEY_VRF_KEY=/workspace/keys/bp-keys/vrf.skey
      - CARDANO_SHELLEY_OPERATIONAL_CERTIFICATE=/workspace/keys/bp-keys/node.cert
    volumes:
      - cardano-bp-data:/data/db
      - cardano-bp-ipc:/ipc
      - .:/workspace
    working_dir: /workspace
    restart: unless-stopped
    command: run
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  cardano-relay-data:
  cardano-relay-ipc:
  cardano-bp-data:
  cardano-bp-ipc:
